language: java

jdk:
  - oraclejdk8

script:
- ./gradlew clean check

before_deploy:
  - chmod +x .buildscript/deploy.sh

deploy:
  provider: script
  script: .buildscript/deploy.sh
  on:
    branch: master

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# only run follow branches
branches:
  only:
  - master
  - develop