language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check

before_deploy:
  - chmod +x .buildscript/deploy.sh
  - chmod +x .buildscript/deploy_snapshot.sh

deploy:
  # deploy release build to maven repo
  - provider: script
    script: .buildscript/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  # deploy snapshot build to snapshot repo
  - provider: script
    script: .buildscript/deploy_snapshot.sh
    skip_cleanup: true
    on:
      branch: snapshot

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# only run follow branches
branches:
  only:
  - master
  - develop
  - snapshot